package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {
//PH> Sous-classe qui implémente l'interface ApiService.

    //PH> Appelle la méthode 'generateUsers' pour initialiser la liste des utilisateurs courante.
    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        //PH> Doit renvoyer la liste des utilisateurs courante.
        
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        //PH> Doit extraire aléatoirement un utilisateur de la liste FAKE_USERS_RANDOM...
        //PH> ...et l'ajouter à la fin de la liste des utilisateurs courante.
        
        users.add(User.random());
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        //PH> Doit supprimer de la liste des utilisateurs courante l'utilisateur passé en paramètre.
        
        users.remove(user);
    }
}
